/* eslint-disable */
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

declare module "@apollo/client" {

  export function useQuery(source: "\n  query Account($slug: String!) {\n    account(slug: $slug) {\n      id\n      slug\n      createdAt\n      description\n      admins: members(role: [ADMIN], limit: 0) {\n        totalCount\n      }\n\n      updates(limit: 3, onlyPublishedUpdates: true) {\n        totalCount\n        nodes {\n          title\n          createdAt\n          slug\n          summary\n          fromAccount {\n            id\n            name\n            imageUrl\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').AccountDocument;
  export function useQuery(source: "\n  query Updates($host: [AccountReferenceInput], $tag: [String], $limit: Int, $offset: Int) {\n    updates(host: $host, accountTag: $tag, accountType: [COLLECTIVE, FUND], limit: $limit, offset: $offset) {\n      totalCount\n      offset\n      nodes {\n        id\n        title\n        createdAt\n        slug\n        summary\n        account {\n          slug\n          imageUrl\n          name\n        }\n        fromAccount {\n          id\n          name\n          imageUrl\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').UpdatesDocument;
  export function useQuery(source: "\n  query SearchAccounts(\n    $host: [AccountReferenceInput]\n    $quarterFrom: DateTime\n    $quarterTo: DateTime\n    $yearFrom: DateTime\n    $yearTo: DateTime\n    $currency: Currency\n    $limit: Int\n    $offset: Int\n  ) {\n    accounts(type: [COLLECTIVE, FUND], limit: $limit, offset: $offset, host: $host) {\n      totalCount\n      offset\n      limit\n      nodes {\n        name\n        slug\n        imageUrl\n        tags\n        location {\n          country\n        }\n        ... on AccountWithHost {\n          host {\n            slug\n            name\n          }\n        }\n\n        ALL: stats {\n          contributorsCount(includeChildren: true)\n          totalAmountSpent(net: true, includeChildren: true, currency: $currency) {\n            valueInCents\n          }\n          totalAmountReceivedTimeSeries(net: true, timeUnit: YEAR, includeChildren: true, currency: $currency) {\n            timeUnit\n            nodes {\n              date\n              amount {\n                valueInCents\n              }\n            }\n          }\n        }\n\n        PAST_YEAR: stats {\n          contributorsCount(includeChildren: true, dateFrom: $yearFrom, dateTo: $yearTo)\n          totalAmountSpent(\n            net: true\n            includeChildren: true\n            dateFrom: $yearFrom\n            dateTo: $yearTo\n            currency: $currency\n          ) {\n            valueInCents\n          }\n          totalAmountReceivedTimeSeries(\n            net: true\n            dateFrom: $yearFrom\n            dateTo: $yearTo\n            timeUnit: MONTH\n            includeChildren: true\n            currency: $currency\n          ) {\n            timeUnit\n            nodes {\n              date\n              amount {\n                valueInCents\n              }\n            }\n          }\n        }\n\n        PAST_QUARTER: stats {\n          contributorsCount(includeChildren: true, dateFrom: $quarterFrom, dateTo: $quarterTo)\n          totalAmountSpent(\n            net: true\n            includeChildren: true\n            dateFrom: $quarterFrom\n            dateTo: $quarterTo\n            currency: $currency\n          ) {\n            valueInCents\n          }\n          totalAmountReceivedTimeSeries(\n            net: true\n            dateFrom: $quarterFrom\n            dateTo: $quarterTo\n            timeUnit: WEEK\n            includeChildren: true\n            currency: $currency\n          ) {\n            timeUnit\n            nodes {\n              date\n              amount {\n                valueInCents\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').SearchAccountsDocument;
  export function useQuery(source: "\n  query OAuthLoggedInUser {\n    me {\n      id\n      name\n      email\n      imageUrl(height: 90)\n      type\n    }\n  }\n"): typeof import('./graphql').OAuthLoggedInUserDocument;
  export function useQuery(source: string): unknown;

    export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<    infer TType,    any  >    ? TType    : never;  
}